name: adatypes
description: A Dart inplementation of various Ada types
version: 0.1.0
repository: https://github.com/shamblett/adatypes
homepage: https://github.com/shamblett/adatypes

funding:
  - https://www.darticulate.com/#funding

publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  test: '^1.23.1'
  lints: '^2.0.1'
