name: adatypes
description: A Dart inplementation of various Ada types
version: 0.2.0
repository: https://github.com/shamblett/adatypes
homepage: https://github.com/shamblett/adatypes

funding:
  - https://www.darticulate.com/#funding

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: '^1.24.2'
  lints: '^2.1.0'
